version: '3.9'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:mine
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html/
    networks:
      - front_network
    depends_on:
      - wordpress

  wordpress:
    build: 
      context: ./requirements/wordpress/
      args:
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USER_NAME=${DATABASE_USER_NAME}
        - DATABASE_USER_PASS=${DATABASE_USER_PASS}
        - DATABASE_HOST=${DATABASE_HOST}
    image: wordpress:mine
    restart: on-failure
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wp:/var/www/html/
    networks:
      - front_network
      - back_network
    depends_on:
      - mariadb
      - redis

  mariadb:
    build: 
      context: ./requirements/mariadb/
      args:
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USER_NAME=${DATABASE_USER_NAME}
        - DATABASE_USER_PASS=${DATABASE_USER_PASS}
    image: mariadb:mine
    restart: on-failure
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql/
    networks:
      - back_network

  redis:
    build: ./requirements/bonus/redis/
    image: redis:mine
    restart: on-failure
    expose:
     - 6379
    networks:
      - back_network
  
  ftp:
    build: 
      context: ./requirements/bonus/ftp
      args:
        - FTP_NAME=${FTP_NAME}
        - FTP_PASS=${FTP_PASS}
    image: ftp:mine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "20-21:20-21"
      - "990:990"
      - "65000-65042:65000-65042"
    volumes:
      - wp:/var/www/html/
    depends_on:
      - wordpress

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db

networks:
  front_network:
  back_network: