#!/bin/bash

cd /var/www/html

# wp core install --url=aalsuwai.42.fr --title=coolPage --admin_user=coolUser --admin_password=amaZingpAsswOrd --admin_email=aalsuwai@student.42abudhabi.ae --allow-root
wp core install --url=localhost --title=${WP_TITLE} --admin_user=${ADMIN_NAME} --admin_password=${ADMIN_PASS} --admin_email=${ADMIN_EMAIL} --allow-root
wp user create ${USER_NAME} ${USER_EMAIL} --role=${USER_ROLE} --user_pass=${USER_PASS} --allow-root

wp theme install ketos --activate --allow-root

wp plugin install redis-cache --activate --allow-root
wp redis enable --allow-root
wp plugin install query-monitor --activate --allow-root

cd ../../..

service php7.3-fpm start && service php7.3-fpm stop
php-fpm7.3 -R --nodaemonize